# Generated by Django 5.1.1 on 2025-01-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesdata',
            name='timestamp',
            field=models.DateTimeField(help_text="Timestamp as received from source (interpreted using measurement's source_timezone)"),
        ),
    ]
