# Generated by Django 5.1.1 on 2024-12-28 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='main.project'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='main.location'),
        ),
    ]
