# Generated by Django 5.1.1 on 2025-01-07 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_datasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIDataSource',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.datasource')),
                ('url_base', models.URLField(help_text='Base URL for the API')),
                ('middleware_type', models.CharField(choices=[('niagara', 'Niagara AX/N4'), ('ecostruxure', 'EcoStruxure Building'), ('metasys', 'Johnson Controls Metasys'), ('desigo', 'Siemens Desigo CC'), ('custom', 'Custom API')], help_text='Type of middleware system', max_length=20)),
                ('auth_type', models.CharField(choices=[('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('oauth2', 'OAuth 2.0'), ('cert', 'Client Certificate')], max_length=20)),
            ],
            bases=('main.datasource',),
        ),
    ]
