# Generated by Django 5.1.1 on 2025-01-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_apidatasource'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_identifiers', models.JSONField(help_text='All identifiers needed to uniquely locate this point in the source system')),
                ('mapping_config', models.JSONField(default=dict, help_text='Data handling configuration (scaling, units, polling)')),
                ('last_sync', models.DateTimeField(null=True)),
                ('last_error', models.TextField(blank=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datasource')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_mappings', to='main.measurement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('measurement', 'data_source'), name='unique_measurement_source')],
            },
        ),
    ]
