# Generated by Django 5.1.1 on 2025-01-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
