# Generated by Django 5.1.1 on 2025-01-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_datasourcemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='UTC timestamp')),
                ('value', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='main.measurement')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['measurement', 'timestamp'], name='main_timese_measure_1911dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('timestamp', 'measurement'), name='unique_measurement_timestamp')],
            },
        ),
    ]
