# Generated by Django 5.1.1 on 2025-01-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_client_delete_client'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_measurement_name_per_location'),
        ),
    ]
