# Generated by Django 5.1.1 on 2025-01-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_timeseriesdata_timestamp_dataimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesdata',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text='UTC timestamp'),
        ),
    ]
