# Generated by Django 5.1.1 on 2025-01-04 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_measurementtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='imports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', 'File Uploaded'), ('analyzed', 'Data Analyzed'), ('mapped', 'Measurements Mapped'), ('imported', 'Data Imported'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('stats', models.JSONField(default=dict)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.measurement')),
            ],
            options={
                'indexes': [models.Index(fields=['measurement', 'timestamp'], name='main_timese_measure_1911dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('timestamp', 'measurement'), name='unique_measurement_timestamp')],
            },
        ),
    ]
