# Generated by Django 5.1.1 on 2025-01-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_dataimport_timeseriesdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_type',
        ),
    ]
